#!/bin/bash
#
#skripti algus
#Teeb praks4a backupi
tar -czf /home/user/skriptimine/praks4a/backup/test.tar.gz 
#Kuvab antud kirja pärast pakkimist
echo "Antud kataloogi /home/user/skriptimine/praks4a/test backupi nimi on test.tar.gz ja see asub /home/user/skriptimine/praks4a/backup kaustas"
#
#skripti lõpp
