#!/bin/bash
#
#Skripti algus
echo -e "Sisesta kuu number : \c"
read kuu
if test $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12
then 
echo "Praegu on talv!"
elif test $kuu -ge 3 -a $kuu -le 5 #Kui sisestad ikka 3,5 siis on kevad
then
echo "Praegu on kevad!"
elif test $kuu -ge 6 -a $kuu -le 8 #Kui sisestad 6,8 siis on ikka suvi
then
echo "Praegu on suvi!"
elif test $kuu -ge 9 -a $kuu -le 11 #Kui sisestad vale kuu ütleb et see ei eksisteeri
then
echo "Praegu on sügis!"
else 
echo "Sellist kuud ei eksisteeri maailmas!"
fi
#Skripti lõpp
