#!/bin/bash
#
#Skripti algus
osch=0
unix="Unix (Sun Os)"
linux="Linux (Red Hat)"
echo "1. $unix"
echo "2. $linux"
echo -n "Select your operating system of choice (1 or 2):" 
read osch
if [ $osch -eq 1 ]; then
echo "You chose $unix"
else
if [ $osch -eq 2 ]; then
echo "You chose $linux"
else 
echo "You must be microsoft fanboy."
fi
fi
#Skripti lõpp
