#!/bin/bash
#
#Skripti algus
echo -n "Palun sisestage suvaline arv:"
read arv
if [ $arv -eq 0 -o $arv -eq 1 ];
then
echo "Antud arv $arv ei ole algarv"
else 
jagaja=2
jaak=$(($arv % $jagaja))
while [ $jaak -ne 0 ]
do
jagaja=$(($jagaja + 1))
jaak=$(($arv % $jagaja))
done
if [ $arv -eq $jagaja ];
then
echo "Antud arv $arv on algarv"
else
echo "Antud arv $arv ei ole algarv"
fi
fi
#Skripti lõpp
