#!/bin/bash
#
# Masina tööaja skript
#
echo `hostname` at `date +"%H:%M:%S"` `uptime -p` # näitab kui kaua masin on töötanud tundides ja minutites 
# hostname nöitab masina nime
#date näitab kellaega 
# skripti lõpp

